<?php

namespace App\Http\Requests;

use App\Enums\StoreCategoryDisplayType;
use App\Enums\StoreComparisonFieldType;
use App\Models\StoreCategory;
use Gate;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class CreateStoreCategoryRequest extends FormRequest
{
    public function authorize(): bool
    {
        return Gate::allows('create', StoreCategory::class);
    }

    /**
     * The slug is derived from the name rather than accepted from the client, so uniqueness can
     * be validated against the value that will actually be stored.
     */
    protected function prepareForValidation(): void
    {
        $this->merge(['slug' => Str::slug((string) $this->input('name'))]);
    }

    public function rules(): array
    {
        return array_merge($this->baseRules(), [
            'slug' => 'required|string|max:255|unique:store_categories,slug',
        ]);
    }

    /**
     * Shared with UpdateStoreCategoryRequest so the two cannot drift apart.
     *
     * @return array<string, mixed>
     */
    public function baseRules(): array
    {
        return [
            'name' => 'required|string|max:255',
            'description' => 'nullable|string|max:5000',
            'parent_id' => 'nullable|integer|exists:store_categories,id',
            'sort_order' => 'nullable|integer|min:0',
            'is_visible' => 'required|boolean',
            'is_enabled' => 'required|boolean',
            'photo' => 'nullable|image|max:5120',

            'display_type' => ['required', Rule::enum(StoreCategoryDisplayType::class)],

            // Rows of the comparison table. The key is generated by the form and round-trips, so a
            // renamed row keeps the values packages already hold against it.
            'comparison_fields' => 'nullable|array|max:20',
            'comparison_fields.*.key' => 'required|string|max:64|regex:/^[a-z0-9_]+$/|distinct',
            'comparison_fields.*.name' => 'required|string|max:255',
            'comparison_fields.*.description' => 'nullable|string|max:255',
            'comparison_fields.*.type' => ['required', Rule::enum(StoreComparisonFieldType::class)],

            'is_cumulative' => 'required|boolean',
        ];
    }

    public function messages(): array
    {
        return [
            'comparison_fields.*.name.required' => __('Every comparison field needs a name.'),
        ];
    }
}
